# Generated by Django 3.0.3 on 2020-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bot1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req1', models.CharField(max_length=1000)),
                ('res1', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='bot2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req2', models.CharField(max_length=1000)),
                ('res2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='bot3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req3', models.CharField(max_length=1000)),
                ('res3', models.CharField(max_length=1000)),
            ],
        ),
    ]
