# Generated by Django 3.0.3 on 2020-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot3',
            name='Ousestion',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
